Разбил логику работы приложения на несколько  частей, работа по генер…
AndreyENR34/MovieQuiz-ios pull request #4
Opened 2023-01-25 05:17 UTC by AndreyENR34

…ации кивков вынесена в отдельную сущность,  написал отдельный класс для ведения статистики и фиксации в памяти лучшего результата, статистика сохраняется в UserDefolts.

2023-01-25 20:10 UTC, mmbabaev requested changes

2023-01-25 20:10 UTC, mmbabaev commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    weak var delegate: AlertDelegate?
private

2023-01-25 20:10 UTC, mmbabaev commented on MovieQuiz/Presentation/AlertPresenter.swift
> +        // создаем объекты всплывающего окна
лучше удалить учебные комментарии

2023-01-25 20:10 UTC, mmbabaev commented on MovieQuiz/Presentation/AlertPresenter.swift
> +        }
скачет форматирование. Предлагаю использовать `cmd+A` + `ctrl+I`

2023-01-25 20:10 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    private var statisticService = StatisticServiceImplementation()
эта переменная должна иметь тип протокола

2023-01-25 20:10 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                text: "Ваш результат: \(correctAnswers)/\(questionsAmount) \n Количество сыграных квизов: \(statisticService.gamesCount) \n Рекорд: \(statisticService.bestGame.correct)/\(questionsAmo
можно использовать тройные кавычки
```
let banner = """
          __,
         (           o  /) _/_
          `.  , , , ,  //  /
        (___)(_(_/_(_ //_ (__
                     /)
                    (/
        """
```

2023-01-25 20:10 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        let fileName = "top250MoviesIMDB.json"
уберите учебный код

2023-01-25 20:10 UTC, mmbabaev commented on MovieQuiz/Services/QuestionFactory.swift
> +    init(delegate: QuestionFactoryDelegate) {
init принято писать под свойствами

2023-01-25 20:10 UTC, mmbabaev commented on MovieQuiz/Services/StatisticService.swift
> +     //userDefaults = UserDefaults.standard
удалите закомментированный код

2023-01-26 07:20 UTC, AndreyENR34 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    weak var delegate: AlertDelegate?
Приветствую! После добавления private к классу AlertPresenter, программа падает в ошибку, не видит данный класс в основном классе. Еще хотелось бы понять, почему приложение до отправки на ревью нормально работало, а после ревью у меня тоже упало в ошибку по отсутствию set в свойствах переменных, после их добавления все заработало, но если откатиться к последнему коммиту( перед отправкой на ревью) то все работает и без них.

2023-01-26 07:31 UTC, AndreyENR34 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +        }
Спасибо, очень удобно!

2023-01-26 07:32 UTC, AndreyENR34 commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    weak var delegate: AlertDelegate?
Понял про приват, это относилось к делегату, исправил.

2023-01-26 08:38 UTC, AndreyENR34 commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +                text: "Ваш результат: \(correctAnswers)/\(questionsAmount) \n Количество сыграных квизов: \(statisticService.gamesCount) \n Рекорд: \(statisticService.bestGame.correct)/\(questionsAmo
Не понимаю, как это применить?

2023-01-26 17:43 UTC, mmbabaev approved these changes

2023-01-26 17:43 UTC, mmbabaev commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +            totalCorrectAnswer = (Double(statisticService.totalAccuracy)*Double(questionsAmount)*Double(statisticService.gamesCount-1)) + Double(correctAnswers)
разделяйте такие длинные выражения на несколько строк

2023-01-27 04:13 UTC, merged